
with open(r'c:/Users/farze/Downloads/funoonai website/funoon-ai-website.html', 'r', encoding='utf-8') as f:
    c = f.read()

start = c.find('// ===== CHATBOT =====')
end   = c.find('\nfunction sendToWhatsApp')
assert start != -1 and end != -1

new_chatbot = (
"// ===== CHATBOT =====\n"
"document.addEventListener('DOMContentLoaded', function () {\n"
"  var tog   = document.getElementById('chat-toggle');\n"
"  var panel = document.getElementById('chat-panel');\n"
"  var bd    = document.getElementById('cb-body');\n"
"  var inp   = document.getElementById('cb-input');\n"
"  var snd   = document.getElementById('cb-send');\n"
"  var started = false;\n"
"\n"
"  // API URL — set window.FUNOON_CHAT_API before this script to override\n"
"  var API = (window.FUNOON_CHAT_API || 'http://localhost:5001') + '/chat';\n"
"\n"
"  // Session ID persisted across page refreshes\n"
"  var SID = sessionStorage.getItem('_wasel_sid');\n"
"  if (!SID) {\n"
"    SID = 'web_' + Math.random().toString(36).slice(2) + Date.now().toString(36);\n"
"    sessionStorage.setItem('_wasel_sid', SID);\n"
"  }\n"
"\n"
"  function callAPI(message, cb) {\n"
"    fetch(API, {\n"
"      method: 'POST',\n"
"      headers: { 'Content-Type': 'application/json' },\n"
"      body: JSON.stringify({ session_id: SID, message: message })\n"
"    })\n"
"    .then(function(r){ return r.json(); })\n"
"    .then(function(d){ cb(null, d.reply || '\u2026'); })\n"
"    .catch(function(e){ cb(e); });\n"
"  }\n"
"\n"
"  tog.addEventListener('click', function () {\n"
"    var open = panel.classList.toggle('open');\n"
"    tog.classList.toggle('open', open);\n"
"    if (open && !started) {\n"
"      started = true;\n"
"      var t = showTyping();\n"
"      callAPI('__INIT__', function(err, reply) {\n"
"        t.remove();\n"
"        if (err) { addMsg('bot', 'Hi! I\\'m Wasel \ud83d\udc4b How can I help?'); return; }\n"
"        addMsg('bot', reply);\n"
"        addQR(['See a Demo', 'Pricing', 'How it works', 'Talk to a human']);\n"
"      });\n"
"    }\n"
"  });\n"
"\n"
"  function onSend(text) {\n"
"    if (!text) return;\n"
"    document.querySelectorAll('.cb-quick').forEach(function(el){ el.remove(); });\n"
"    addMsg('user', text);\n"
"    var t = showTyping();\n"
"    callAPI(text, function(err, reply) {\n"
"      t.remove();\n"
"      addMsg('bot', err ? 'Something went wrong \u2014 try again or email hello@funoon.ai' : reply);\n"
"    });\n"
"  }\n"
"\n"
"  function addMsg(role, text) {\n"
"    var el = document.createElement('div');\n"
"    el.className = 'cb-msg ' + role;\n"
"    el.textContent = text;\n"
"    bd.appendChild(el);\n"
"    bd.scrollTop = bd.scrollHeight;\n"
"    setTimeout(function(){ el.classList.add('show'); }, 20);\n"
"  }\n"
"\n"
"  function addQR(opts) {\n"
"    var wrap = document.createElement('div');\n"
"    wrap.className = 'cb-quick';\n"
"    opts.forEach(function(opt) {\n"
"      var b = document.createElement('button');\n"
"      b.className = 'cb-qr';\n"
"      b.textContent = opt;\n"
"      b.onclick = function(){ onSend(opt); };\n"
"      wrap.appendChild(b);\n"
"    });\n"
"    bd.appendChild(wrap);\n"
"    bd.scrollTop = bd.scrollHeight;\n"
"  }\n"
"\n"
"  function showTyping() {\n"
"    var t = document.createElement('div');\n"
"    t.className = 'cb-typing';\n"
"    t.innerHTML = '<span></span><span></span><span></span>';\n"
"    bd.appendChild(t);\n"
"    bd.scrollTop = bd.scrollHeight;\n"
"    return t;\n"
"  }\n"
"\n"
"  snd.addEventListener('click', function(){\n"
"    var v = inp.value.trim();\n"
"    if (!v) return;\n"
"    inp.value = '';\n"
"    onSend(v);\n"
"  });\n"
"\n"
"  inp.addEventListener('keydown', function(e){\n"
"    if (e.key === 'Enter') { snd.click(); }\n"
"  });\n"
"});\n"
"\n"
)

c = c[:start] + new_chatbot + c[end:]

with open(r'c:/Users/farze/Downloads/funoonai website/funoon-ai-website.html', 'w', encoding='utf-8') as f:
    f.write(c)
print('Done. Size:', len(c))
